// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/prober/proto/service.proto

package proto

import (
	proto "github.com/cloudprober/cloudprober/probes/proto"
	proto1 "github.com/cloudprober/cloudprober/targets/endpoint/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProbeConfig *proto.ProbeDef `protobuf:"bytes,1,opt,name=probe_config,json=probeConfig" json:"probe_config,omitempty"`
}

func (x *AddProbeRequest) Reset() {
	*x = AddProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProbeRequest) ProtoMessage() {}

func (x *AddProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProbeRequest.ProtoReflect.Descriptor instead.
func (*AddProbeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddProbeRequest) GetProbeConfig() *proto.ProbeDef {
	if x != nil {
		return x.ProbeConfig
	}
	return nil
}

type AddProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddProbeResponse) Reset() {
	*x = AddProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProbeResponse) ProtoMessage() {}

func (x *AddProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProbeResponse.ProtoReflect.Descriptor instead.
func (*AddProbeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{1}
}

type RemoveProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProbeName *string `protobuf:"bytes,1,opt,name=probe_name,json=probeName" json:"probe_name,omitempty"`
}

func (x *RemoveProbeRequest) Reset() {
	*x = RemoveProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProbeRequest) ProtoMessage() {}

func (x *RemoveProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProbeRequest.ProtoReflect.Descriptor instead.
func (*RemoveProbeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveProbeRequest) GetProbeName() string {
	if x != nil && x.ProbeName != nil {
		return *x.ProbeName
	}
	return ""
}

type RemoveProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveProbeResponse) Reset() {
	*x = RemoveProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProbeResponse) ProtoMessage() {}

func (x *RemoveProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProbeResponse.ProtoReflect.Descriptor instead.
func (*RemoveProbeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{3}
}

type RunProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If empty, all configured probes are run.
	ProbeName []string `protobuf:"bytes,1,rep,name=probe_name,json=probeName" json:"probe_name,omitempty"`
}

func (x *RunProbeRequest) Reset() {
	*x = RunProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunProbeRequest) ProtoMessage() {}

func (x *RunProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunProbeRequest.ProtoReflect.Descriptor instead.
func (*RunProbeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *RunProbeRequest) GetProbeName() []string {
	if x != nil {
		return x.ProbeName
	}
	return nil
}

// TODO: Add metrics handling.
type ResultMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultMetric) Reset() {
	*x = ResultMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMetric) ProtoMessage() {}

func (x *ResultMetric) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMetric.ProtoReflect.Descriptor instead.
func (*ResultMetric) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{5}
}

// Results of a single probe run for a given target.
type ProbeRunResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Target that this result is associated with.
	Target *proto1.Endpoint `protobuf:"bytes,1,req,name=target" json:"target,omitempty"`
	// True if the probe run was successful.
	Success *bool `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	// Latency in microseconds. Set for successful probes.
	LatencyUsec *int64 `protobuf:"varint,3,opt,name=latency_usec,json=latencyUsec" json:"latency_usec,omitempty"`
	// Additional metrics from the probe run.
	ResultMetrics []*ResultMetric `protobuf:"bytes,4,rep,name=result_metrics,json=resultMetrics" json:"result_metrics,omitempty"`
	// Optional error message for failed probes.
	Error *string `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (x *ProbeRunResult) Reset() {
	*x = ProbeRunResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRunResult) ProtoMessage() {}

func (x *ProbeRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRunResult.ProtoReflect.Descriptor instead.
func (*ProbeRunResult) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeRunResult) GetTarget() *proto1.Endpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ProbeRunResult) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *ProbeRunResult) GetLatencyUsec() int64 {
	if x != nil && x.LatencyUsec != nil {
		return *x.LatencyUsec
	}
	return 0
}

func (x *ProbeRunResult) GetResultMetrics() []*ResultMetric {
	if x != nil {
		return x.ResultMetrics
	}
	return nil
}

func (x *ProbeRunResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ProbeResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunResult []*ProbeRunResult `protobuf:"bytes,1,rep,name=run_result,json=runResult" json:"run_result,omitempty"`
}

func (x *ProbeResults) Reset() {
	*x = ProbeResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResults) ProtoMessage() {}

func (x *ProbeResults) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResults.ProtoReflect.Descriptor instead.
func (*ProbeResults) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProbeResults) GetRunResult() []*ProbeRunResult {
	if x != nil {
		return x.RunResult
	}
	return nil
}

type RunProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results map[string]*ProbeResults `protobuf:"bytes,1,rep,name=results" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *RunProbeResponse) Reset() {
	*x = RunProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunProbeResponse) ProtoMessage() {}

func (x *RunProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunProbeResponse.ProtoReflect.Descriptor instead.
func (*RunProbeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *RunProbeResponse) GetResults() map[string]*ProbeResults {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListProbesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListProbesRequest) Reset() {
	*x = ListProbesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProbesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProbesRequest) ProtoMessage() {}

func (x *ListProbesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProbesRequest.ProtoReflect.Descriptor instead.
func (*ListProbesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{9}
}

type Probe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   *string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Config *proto.ProbeDef `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (x *Probe) Reset() {
	*x = Probe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *Probe) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Probe) GetConfig() *proto.ProbeDef {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListProbesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Probe []*Probe `protobuf:"bytes,1,rep,name=probe" json:"probe,omitempty"`
}

func (x *ListProbesResponse) Reset() {
	*x = ListProbesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProbesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProbesResponse) ProtoMessage() {}

func (x *ListProbesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProbesResponse.ProtoReflect.Descriptor instead.
func (*ListProbesResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListProbesResponse) GetProbe() []*Probe {
	if x != nil {
		return x.Probe
	}
	return nil
}

type SaveProbesConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// File path to save probes config to. Default is configured through the
	// command-line flag: --probes_config_save_path
	FilePath *string `protobuf:"bytes,1,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
}

func (x *SaveProbesConfigRequest) Reset() {
	*x = SaveProbesConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveProbesConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProbesConfigRequest) ProtoMessage() {}

func (x *SaveProbesConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProbesConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveProbesConfigRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *SaveProbesConfigRequest) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

type SaveProbesConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath *string `protobuf:"bytes,1,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
}

func (x *SaveProbesConfigResponse) Reset() {
	*x = SaveProbesConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveProbesConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProbesConfigResponse) ProtoMessage() {}

func (x *SaveProbesConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProbesConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveProbesConfigResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *SaveProbesConfigResponse) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

var File_github_com_cloudprober_cloudprober_prober_proto_service_proto protoreflect.FileDescriptor

var file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x1a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x48, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x44, 0x65, 0x66, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x12,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x62, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0xdc, 0x01, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x35, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x55, 0x73, 0x65,
	0x63, 0x12, 0x40, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4a, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x72, 0x75, 0x6e,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x1a, 0x55, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x05,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x44, 0x65, 0x66, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x3e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x22,
	0x36, 0x0a, 0x17, 0x53, 0x61, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x37, 0x0a, 0x18, 0x53, 0x61, 0x76, 0x65, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x32, 0xab, 0x03, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x12, 0x49, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1c, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x10, 0x53,
	0x61, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x24, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f,
}

var (
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescData = file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDesc
)

func file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescData)
	})
	return file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_github_com_cloudprober_cloudprober_prober_proto_service_proto_goTypes = []interface{}{
	(*AddProbeRequest)(nil),          // 0: cloudprober.AddProbeRequest
	(*AddProbeResponse)(nil),         // 1: cloudprober.AddProbeResponse
	(*RemoveProbeRequest)(nil),       // 2: cloudprober.RemoveProbeRequest
	(*RemoveProbeResponse)(nil),      // 3: cloudprober.RemoveProbeResponse
	(*RunProbeRequest)(nil),          // 4: cloudprober.RunProbeRequest
	(*ResultMetric)(nil),             // 5: cloudprober.ResultMetric
	(*ProbeRunResult)(nil),           // 6: cloudprober.ProbeRunResult
	(*ProbeResults)(nil),             // 7: cloudprober.ProbeResults
	(*RunProbeResponse)(nil),         // 8: cloudprober.RunProbeResponse
	(*ListProbesRequest)(nil),        // 9: cloudprober.ListProbesRequest
	(*Probe)(nil),                    // 10: cloudprober.Probe
	(*ListProbesResponse)(nil),       // 11: cloudprober.ListProbesResponse
	(*SaveProbesConfigRequest)(nil),  // 12: cloudprober.SaveProbesConfigRequest
	(*SaveProbesConfigResponse)(nil), // 13: cloudprober.SaveProbesConfigResponse
	nil,                              // 14: cloudprober.RunProbeResponse.ResultsEntry
	(*proto.ProbeDef)(nil),           // 15: cloudprober.probes.ProbeDef
	(*proto1.Endpoint)(nil),          // 16: cloudprober.targets.Endpoint
}
var file_github_com_cloudprober_cloudprober_prober_proto_service_proto_depIdxs = []int32{
	15, // 0: cloudprober.AddProbeRequest.probe_config:type_name -> cloudprober.probes.ProbeDef
	16, // 1: cloudprober.ProbeRunResult.target:type_name -> cloudprober.targets.Endpoint
	5,  // 2: cloudprober.ProbeRunResult.result_metrics:type_name -> cloudprober.ResultMetric
	6,  // 3: cloudprober.ProbeResults.run_result:type_name -> cloudprober.ProbeRunResult
	14, // 4: cloudprober.RunProbeResponse.results:type_name -> cloudprober.RunProbeResponse.ResultsEntry
	15, // 5: cloudprober.Probe.config:type_name -> cloudprober.probes.ProbeDef
	10, // 6: cloudprober.ListProbesResponse.probe:type_name -> cloudprober.Probe
	7,  // 7: cloudprober.RunProbeResponse.ResultsEntry.value:type_name -> cloudprober.ProbeResults
	0,  // 8: cloudprober.Cloudprober.AddProbe:input_type -> cloudprober.AddProbeRequest
	2,  // 9: cloudprober.Cloudprober.RemoveProbe:input_type -> cloudprober.RemoveProbeRequest
	4,  // 10: cloudprober.Cloudprober.RunProbe:input_type -> cloudprober.RunProbeRequest
	9,  // 11: cloudprober.Cloudprober.ListProbes:input_type -> cloudprober.ListProbesRequest
	12, // 12: cloudprober.Cloudprober.SaveProbesConfig:input_type -> cloudprober.SaveProbesConfigRequest
	1,  // 13: cloudprober.Cloudprober.AddProbe:output_type -> cloudprober.AddProbeResponse
	3,  // 14: cloudprober.Cloudprober.RemoveProbe:output_type -> cloudprober.RemoveProbeResponse
	8,  // 15: cloudprober.Cloudprober.RunProbe:output_type -> cloudprober.RunProbeResponse
	11, // 16: cloudprober.Cloudprober.ListProbes:output_type -> cloudprober.ListProbesResponse
	13, // 17: cloudprober.Cloudprober.SaveProbesConfig:output_type -> cloudprober.SaveProbesConfigResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_prober_proto_service_proto_init() }
func file_github_com_cloudprober_cloudprober_prober_proto_service_proto_init() {
	if File_github_com_cloudprober_cloudprober_prober_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeRunResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProbesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Probe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProbesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveProbesConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveProbesConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_prober_proto_service_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_prober_proto_service_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_prober_proto_service_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_prober_proto_service_proto = out.File
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_rawDesc = nil
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_prober_proto_service_proto_depIdxs = nil
}
