# Dockerfile for quick development and testing
# To build:
#    docker build -t cloudprober:test . -f Dockerfile.dev
FROM golang:1.18-alpine as build

WORKDIR /app
COPY . /
RUN go build -o /cloudprober /cmd/cloudprober.go 

FROM alpine
COPY --from=build /cloudprober /cloudprober
COPY cloudprober_test.cfg /etc/cloudprober.cfg
ENTRYPOINT ["/cloudprober", "--logtostderr"]
