# Dockerfile for quick development and testing
# To build:
#    docker build -t cloudprober:test . -f Dockerfile.dev
FROM golang:1.21-alpine as build

WORKDIR /app
COPY . /
RUN if [[ ! -f /cloudprober ]]; then go build -o /cloudprober /cmd/cloudprober.go; fi 

FROM alpine
COPY --from=build /cloudprober /cloudprober
COPY cmd/cloudprober_test.cfg /etc/cloudprober.cfg
ENTRYPOINT ["/cloudprober"]
