// Code generated by genprotofacade; DO NOT EDIT.
//go:generate go run github.com/cloudprober/cloudprober/tools/genprotofacade -protoroot=internal/alerting -out=$GOFILE

package alerting

import alertingpb "github.com/cloudprober/cloudprober/internal/alerting/proto"

// Symbols from github.com/cloudprober/cloudprober/internal/alerting/proto
const AlertConf_CRITICAL = alertingpb.AlertConf_CRITICAL
const AlertConf_ERROR = alertingpb.AlertConf_ERROR
const AlertConf_INFO = alertingpb.AlertConf_INFO
const AlertConf_UNKNOWN_SEVERITY = alertingpb.AlertConf_UNKNOWN_SEVERITY
const AlertConf_WARNING = alertingpb.AlertConf_WARNING
const Opsgenie_Responder_ESCALATION = alertingpb.Opsgenie_Responder_ESCALATION
const Opsgenie_Responder_SCHEDULE = alertingpb.Opsgenie_Responder_SCHEDULE
const Opsgenie_Responder_TEAM = alertingpb.Opsgenie_Responder_TEAM
const Opsgenie_Responder_UNKNOWN_RESPONDER = alertingpb.Opsgenie_Responder_UNKNOWN_RESPONDER
const Opsgenie_Responder_USER = alertingpb.Opsgenie_Responder_USER
type AlertConf = alertingpb.AlertConf
type AlertConf_Severity = alertingpb.AlertConf_Severity
type Condition = alertingpb.Condition
type Email = alertingpb.Email
type NotifyConfig = alertingpb.NotifyConfig
type Opsgenie = alertingpb.Opsgenie
type Opsgenie_Responder = alertingpb.Opsgenie_Responder
type Opsgenie_Responder_Id = alertingpb.Opsgenie_Responder_Id
type Opsgenie_Responder_Name = alertingpb.Opsgenie_Responder_Name
type Opsgenie_Responder_Type = alertingpb.Opsgenie_Responder_Type
type PagerDuty = alertingpb.PagerDuty
type Slack = alertingpb.Slack


