// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/targets/endpoint/proto/endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint name. Metrics for a target are identified by a combination of
	// endpoint name and port name, if specified.
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// Optional IP address. If not specified, endpoint name is DNS resolved.
	Ip *string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// Endpoint port. If specified, this port will be used by the port-based
	// probes (e.g.  TCP, HTTP), if probe's configuration doesn't specify a port.
	Port *int32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	// HTTP probe URL. If provided, this field is used by the HTTP probe, if
	// probe configuration itself doesn't specify URL fields.
	Url *string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	// Endpoint labels. These labels can be exported as metrics labels using the
	// `additional_label` field in the probe configuration.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoint) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Endpoint) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *Endpoint) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Endpoint) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Endpoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDesc = "" +
	"\n" +
	"Hgithub.com/cloudprober/cloudprober/targets/endpoint/proto/endpoint.proto\x12\x13cloudprober.targets\"\xd2\x01\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).cloudprober.targets.Endpoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B;Z9github.com/cloudprober/cloudprober/targets/endpoint/proto"

var (
	file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_goTypes = []any{
	(*Endpoint)(nil), // 0: cloudprober.targets.Endpoint
	nil,              // 1: cloudprober.targets.Endpoint.LabelsEntry
}
var file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_depIdxs = []int32{
	1, // 0: cloudprober.targets.Endpoint.labels:type_name -> cloudprober.targets.Endpoint.LabelsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_init() }
func file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_init() {
	if File_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto = out.File
	file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_targets_endpoint_proto_endpoint_proto_depIdxs = nil
}
