// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/internal/servers/grpc/proto/grpcservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoMessage) Reset() {
	*x = EchoMessage{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoMessage) ProtoMessage() {}

func (x *EchoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoMessage.ProtoReflect.Descriptor instead.
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{0}
}

func (x *EchoMessage) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    *string                `protobuf:"bytes,1,opt,name=client_name,json=clientName" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{1}
}

func (x *StatusRequest) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeUs      *int64                 `protobuf:"varint,1,opt,name=uptime_us,json=uptimeUs" json:"uptime_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetUptimeUs() int64 {
	if x != nil && x.UptimeUs != nil {
		return *x.UptimeUs
	}
	return 0
}

type BlobReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *int32                 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobReadRequest) Reset() {
	*x = BlobReadRequest{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobReadRequest) ProtoMessage() {}

func (x *BlobReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobReadRequest.ProtoReflect.Descriptor instead.
func (*BlobReadRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{3}
}

func (x *BlobReadRequest) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type BlobReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobReadResponse) Reset() {
	*x = BlobReadResponse{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobReadResponse) ProtoMessage() {}

func (x *BlobReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobReadResponse.ProtoReflect.Descriptor instead.
func (*BlobReadResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{4}
}

func (x *BlobReadResponse) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type BlobWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobWriteRequest) Reset() {
	*x = BlobWriteRequest{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobWriteRequest) ProtoMessage() {}

func (x *BlobWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobWriteRequest.ProtoReflect.Descriptor instead.
func (*BlobWriteRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{5}
}

func (x *BlobWriteRequest) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

type BlobWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *int32                 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobWriteResponse) Reset() {
	*x = BlobWriteResponse{}
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobWriteResponse) ProtoMessage() {}

func (x *BlobWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobWriteResponse.ProtoReflect.Descriptor instead.
func (*BlobWriteResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP(), []int{6}
}

func (x *BlobWriteResponse) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/cloudprober/cloudprober/internal/servers/grpc/proto/grpcservice.proto\x12\x18cloudprober.servers.grpc\"!\n" +
	"\vEchoMessage\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\"0\n" +
	"\rStatusRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\"-\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tuptime_us\x18\x01 \x01(\x03R\buptimeUs\"%\n" +
	"\x0fBlobReadRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"&\n" +
	"\x10BlobReadResponse\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\"&\n" +
	"\x10BlobWriteRequest\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\"'\n" +
	"\x11BlobWriteResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size2\x92\x03\n" +
	"\x06Prober\x12V\n" +
	"\x04Echo\x12%.cloudprober.servers.grpc.EchoMessage\x1a%.cloudprober.servers.grpc.EchoMessage\"\x00\x12c\n" +
	"\bBlobRead\x12).cloudprober.servers.grpc.BlobReadRequest\x1a*.cloudprober.servers.grpc.BlobReadResponse\"\x00\x12c\n" +
	"\fServerStatus\x12'.cloudprober.servers.grpc.StatusRequest\x1a(.cloudprober.servers.grpc.StatusResponse\"\x00\x12f\n" +
	"\tBlobWrite\x12*.cloudprober.servers.grpc.BlobWriteRequest\x1a+.cloudprober.servers.grpc.BlobWriteResponse\"\x00B@Z>github.com/cloudprober/cloudprober/internal/servers/grpc/proto"

var (
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_goTypes = []any{
	(*EchoMessage)(nil),       // 0: cloudprober.servers.grpc.EchoMessage
	(*StatusRequest)(nil),     // 1: cloudprober.servers.grpc.StatusRequest
	(*StatusResponse)(nil),    // 2: cloudprober.servers.grpc.StatusResponse
	(*BlobReadRequest)(nil),   // 3: cloudprober.servers.grpc.BlobReadRequest
	(*BlobReadResponse)(nil),  // 4: cloudprober.servers.grpc.BlobReadResponse
	(*BlobWriteRequest)(nil),  // 5: cloudprober.servers.grpc.BlobWriteRequest
	(*BlobWriteResponse)(nil), // 6: cloudprober.servers.grpc.BlobWriteResponse
}
var file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_depIdxs = []int32{
	0, // 0: cloudprober.servers.grpc.Prober.Echo:input_type -> cloudprober.servers.grpc.EchoMessage
	3, // 1: cloudprober.servers.grpc.Prober.BlobRead:input_type -> cloudprober.servers.grpc.BlobReadRequest
	1, // 2: cloudprober.servers.grpc.Prober.ServerStatus:input_type -> cloudprober.servers.grpc.StatusRequest
	5, // 3: cloudprober.servers.grpc.Prober.BlobWrite:input_type -> cloudprober.servers.grpc.BlobWriteRequest
	0, // 4: cloudprober.servers.grpc.Prober.Echo:output_type -> cloudprober.servers.grpc.EchoMessage
	4, // 5: cloudprober.servers.grpc.Prober.BlobRead:output_type -> cloudprober.servers.grpc.BlobReadResponse
	2, // 6: cloudprober.servers.grpc.Prober.ServerStatus:output_type -> cloudprober.servers.grpc.StatusResponse
	6, // 7: cloudprober.servers.grpc.Prober.BlobWrite:output_type -> cloudprober.servers.grpc.BlobWriteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_init()
}
func file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_init() {
	if File_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto = out.File
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_internal_servers_grpc_proto_grpcservice_proto_depIdxs = nil
}
