[project]
name = "cloudprober-serverutils"
version = "v0.0.0"
description = "Package for Cloudprober's external probe's serverutils"
dependencies = [ "protobuf" ]
readme = "README.md"

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://cloudprober.org"
Repository = "https://github.com/cloudprober/cloudprober"