// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/internal/alerting/proto/config.proto

package proto

import (
	proto "github.com/cloudprober/cloudprober/internal/httpreq/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Opsgenie_Responder_Type int32

const (
	Opsgenie_Responder_UNKNOWN_RESPONDER Opsgenie_Responder_Type = 0
	Opsgenie_Responder_USER              Opsgenie_Responder_Type = 1
	Opsgenie_Responder_TEAM              Opsgenie_Responder_Type = 2
	Opsgenie_Responder_ESCALATION        Opsgenie_Responder_Type = 3
	Opsgenie_Responder_SCHEDULE          Opsgenie_Responder_Type = 4
)

// Enum value maps for Opsgenie_Responder_Type.
var (
	Opsgenie_Responder_Type_name = map[int32]string{
		0: "UNKNOWN_RESPONDER",
		1: "USER",
		2: "TEAM",
		3: "ESCALATION",
		4: "SCHEDULE",
	}
	Opsgenie_Responder_Type_value = map[string]int32{
		"UNKNOWN_RESPONDER": 0,
		"USER":              1,
		"TEAM":              2,
		"ESCALATION":        3,
		"SCHEDULE":          4,
	}
)

func (x Opsgenie_Responder_Type) Enum() *Opsgenie_Responder_Type {
	p := new(Opsgenie_Responder_Type)
	*p = x
	return p
}

func (x Opsgenie_Responder_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opsgenie_Responder_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes[0].Descriptor()
}

func (Opsgenie_Responder_Type) Type() protoreflect.EnumType {
	return &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes[0]
}

func (x Opsgenie_Responder_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Opsgenie_Responder_Type.Descriptor instead.
func (Opsgenie_Responder_Type) EnumDescriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{1, 0, 0}
}

// Severity of the alert. If provided it's included in the alert
// notifications. If severity is not defined, we set it to ERROR for
// PagerDuty notifications.
type AlertConf_Severity int32

const (
	AlertConf_UNKNOWN_SEVERITY AlertConf_Severity = 0
	AlertConf_CRITICAL         AlertConf_Severity = 1
	AlertConf_ERROR            AlertConf_Severity = 2
	AlertConf_WARNING          AlertConf_Severity = 3
	AlertConf_INFO             AlertConf_Severity = 4
)

// Enum value maps for AlertConf_Severity.
var (
	AlertConf_Severity_name = map[int32]string{
		0: "UNKNOWN_SEVERITY",
		1: "CRITICAL",
		2: "ERROR",
		3: "WARNING",
		4: "INFO",
	}
	AlertConf_Severity_value = map[string]int32{
		"UNKNOWN_SEVERITY": 0,
		"CRITICAL":         1,
		"ERROR":            2,
		"WARNING":          3,
		"INFO":             4,
	}
)

func (x AlertConf_Severity) Enum() *AlertConf_Severity {
	p := new(AlertConf_Severity)
	*p = x
	return p
}

func (x AlertConf_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertConf_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes[1].Descriptor()
}

func (AlertConf_Severity) Type() protoreflect.EnumType {
	return &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes[1]
}

func (x AlertConf_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertConf_Severity.Descriptor instead.
func (AlertConf_Severity) EnumDescriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{6, 0}
}

type Email struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email addresses to send the alert to.
	To []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	// From address in the alert email.
	// If not set, defaults to the value of smtp_user if smtp_user is set,
	// otherwise defaults to cloudprober-alert@<hostname>.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Default: Environment variable SMTP_SERVER
	SmtpServer string `protobuf:"bytes,3,opt,name=smtp_server,json=smtpServer,proto3" json:"smtp_server,omitempty"`
	// Default: Environment variable SMTP_USERNAME
	SmtpUsername string `protobuf:"bytes,4,opt,name=smtp_username,json=smtpUsername,proto3" json:"smtp_username,omitempty"`
	// Default: Environment variable SMTP_PASSWORD
	SmtpPassword  string `protobuf:"bytes,5,opt,name=smtp_password,json=smtpPassword,proto3" json:"smtp_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Email) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Email) GetSmtpServer() string {
	if x != nil {
		return x.SmtpServer
	}
	return ""
}

func (x *Email) GetSmtpUsername() string {
	if x != nil {
		return x.SmtpUsername
	}
	return ""
}

func (x *Email) GetSmtpPassword() string {
	if x != nil {
		return x.SmtpPassword
	}
	return ""
}

type Opsgenie struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API key to access Opsgenie. It's usually tied to a team and is
	// obtained by creating a new API integration or using an existing one.
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Environment variable name Default: OPSGENIE_API_KEY
	ApiKeyEnvVar string `protobuf:"bytes,2,opt,name=api_key_env_var,json=apiKeyEnvVar,proto3" json:"api_key_env_var,omitempty"`
	// Opsgenie responders. Opsgenie uses the responders to route the alerts if
	// API key doesn't belong to a team integration.
	// Example:
	//
	//	responders {
	//	  id: "4513b7ea-3b91-438f-b7e4-e3e54af9147c"
	//	  type: TEAM
	//	}
	Responders []*Opsgenie_Responder `protobuf:"bytes,3,rep,name=responders,proto3" json:"responders,omitempty"`
	// Opsgenie API URL.
	// Default: https://api.opsgenie.com/v2/alerts
	ApiUrl string `protobuf:"bytes,4,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	// Whether to send resolve notifications or not. Default is to send resolve
	// notifications.
	DisableSendResolved bool `protobuf:"varint,5,opt,name=disable_send_resolved,json=disableSendResolved,proto3" json:"disable_send_resolved,omitempty"` // Default: false
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Opsgenie) Reset() {
	*x = Opsgenie{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opsgenie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opsgenie) ProtoMessage() {}

func (x *Opsgenie) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opsgenie.ProtoReflect.Descriptor instead.
func (*Opsgenie) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *Opsgenie) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Opsgenie) GetApiKeyEnvVar() string {
	if x != nil {
		return x.ApiKeyEnvVar
	}
	return ""
}

func (x *Opsgenie) GetResponders() []*Opsgenie_Responder {
	if x != nil {
		return x.Responders
	}
	return nil
}

func (x *Opsgenie) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *Opsgenie) GetDisableSendResolved() bool {
	if x != nil {
		return x.DisableSendResolved
	}
	return false
}

type PagerDuty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PagerDuty Routing Key.
	// The routing key is used to authenticate to PagerDuty and is tied to a
	// service. You can obtain the routing key from the service page, under the
	// integrations tab.
	// Note: set either routing_key or routing_key_env_var. routing_key
	// takes precedence over routing_key_env_var.
	RoutingKey string `protobuf:"bytes,1,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	// The environment variable containing the pagerduty routing key.
	// Default: PAGERDUTY_ROUTING_KEY;
	RoutingKeyEnvVar string `protobuf:"bytes,2,opt,name=routing_key_env_var,json=routingKeyEnvVar,proto3" json:"routing_key_env_var,omitempty"`
	// PagerDuty API URL.
	// Used to overwrite the default PagerDuty API URL.
	ApiUrl string `protobuf:"bytes,3,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"` // Default: https://event.pagerduty.com
	// Whether to send resolve notifications or not. Default is to send resolve
	// notifications.
	DisableSendResolved bool `protobuf:"varint,4,opt,name=disable_send_resolved,json=disableSendResolved,proto3" json:"disable_send_resolved,omitempty"` // Default: false
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PagerDuty) Reset() {
	*x = PagerDuty{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagerDuty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagerDuty) ProtoMessage() {}

func (x *PagerDuty) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagerDuty.ProtoReflect.Descriptor instead.
func (*PagerDuty) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *PagerDuty) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *PagerDuty) GetRoutingKeyEnvVar() string {
	if x != nil {
		return x.RoutingKeyEnvVar
	}
	return ""
}

func (x *PagerDuty) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *PagerDuty) GetDisableSendResolved() bool {
	if x != nil {
		return x.DisableSendResolved
	}
	return false
}

type Slack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhook URL
	// The Slack notifications use a webhook URL to send the notifications to
	// a Slack channel. The webhook URL can be found in the Slack console under
	// the "Incoming Webhooks" section.
	// https://api.slack.com/messaging/webhooks
	// Note: set either webhook_url or webhook_url_env_var. webhook_url
	// takes precedence over webhook_url_env_var.
	WebhookUrl string `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	// The environment variable that is used to contain the slack webhook URL.
	WebhookUrlEnvVar string `protobuf:"bytes,2,opt,name=webhook_url_env_var,json=webhookUrlEnvVar,proto3" json:"webhook_url_env_var,omitempty"` // Default: SLACK_WEBHOOK_URL;
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Slack) Reset() {
	*x = Slack{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slack) ProtoMessage() {}

func (x *Slack) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slack.ProtoReflect.Descriptor instead.
func (*Slack) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *Slack) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *Slack) GetWebhookUrlEnvVar() string {
	if x != nil {
		return x.WebhookUrlEnvVar
	}
	return ""
}

type NotifyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command to run when alert is fired. You can use this command to do
	// various things, e.g.:
	//   - Send a notification using a method not supported by Cloudprober.
	//   - Collect more information, e.g. send mtr report on ping failures.
	//   - Attempt fix the issue, e.g. restart a pod or clear cache.
	//
	// In the command line following fields are substituted:
	//
	//	@alert@: Alert name
	//	@probe@: Probe name
	//	@target@: Target name, or target and port if port is specified.
	//	@target.label.<label>@: Label <label> value, e.g. target.label.role.
	//	@failures@: Count of failures.
	//	@total@: Out of.
	//	@since@: Time since the alert condition started.
	//	@json@: JSON representation of the alert fields.
	//
	// For example, if you want to send an email when an alert is fired, you can
	// use the following command:
	// command: "/usr/bin/mail -s 'Alert @alert@ fired for @target@' manu@a.b"
	Command string `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	// Email notification configuration.
	Email *Email `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	// PagerDuty configuration.
	PagerDuty *PagerDuty `protobuf:"bytes,12,opt,name=pager_duty,json=pagerDuty,proto3" json:"pager_duty,omitempty"`
	// Slack configuration.
	Slack *Slack `protobuf:"bytes,13,opt,name=slack,proto3" json:"slack,omitempty"`
	// Opsgenie configuration.
	Opsgenie *Opsgenie `protobuf:"bytes,14,opt,name=opsgenie,proto3" json:"opsgenie,omitempty"`
	// Notify using an HTTP request. HTTP request fields are expanded using the
	// same template expansion rules as "command" above:
	// For example, to send a notification using rest API:
	//
	//	http_notify {
	//	  url: "http://localhost:8080/alert"
	//	  method: POST
	//	  header {
	//	    key: "Authorization"
	//	    value: "Bearer {{env 'AUTH_TOKEN'}}"
	//	  }
	//	  data: "{\"message\": \"@alert@ fired for @target@\", \"details\": \"name\"}"
	//	}
	HttpNotify    *proto.HTTPRequest `protobuf:"bytes,3,opt,name=http_notify,json=httpNotify,proto3" json:"http_notify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyConfig) Reset() {
	*x = NotifyConfig{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyConfig) ProtoMessage() {}

func (x *NotifyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyConfig.ProtoReflect.Descriptor instead.
func (*NotifyConfig) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *NotifyConfig) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *NotifyConfig) GetPagerDuty() *PagerDuty {
	if x != nil {
		return x.PagerDuty
	}
	return nil
}

func (x *NotifyConfig) GetSlack() *Slack {
	if x != nil {
		return x.Slack
	}
	return nil
}

func (x *NotifyConfig) GetOpsgenie() *Opsgenie {
	if x != nil {
		return x.Opsgenie
	}
	return nil
}

func (x *NotifyConfig) GetHttpNotify() *proto.HTTPRequest {
	if x != nil {
		return x.HttpNotify
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failures      int32                  `protobuf:"varint,1,opt,name=failures,proto3" json:"failures,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *Condition) GetFailures() int32 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *Condition) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AlertConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the alert. Default is to use the probe name. If you have multiple
	// alerts for the same probe, you must specify a name for each alert.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Condition for the alert. Default is to alert on any failure.
	// Example:
	// # Alert if 6 out of 10 probes fail.
	//
	//	condition {
	//	  failures: 6
	//	  total: 10
	//	}
	Condition *Condition `protobuf:"bytes,2,opt,name=condition,proto3,oneof" json:"condition,omitempty"`
	// How to notify in case of alert.
	Notify *NotifyConfig `protobuf:"bytes,3,opt,name=notify,proto3" json:"notify,omitempty"`
	// Dashboard URL template.
	// Default: http://localhost:9313/status?probe=@probe@
	DashboardUrlTemplate string `protobuf:"bytes,4,opt,name=dashboard_url_template,json=dashboardUrlTemplate,proto3" json:"dashboard_url_template,omitempty"` // Default: ""
	PlaybookUrlTemplate  string `protobuf:"bytes,5,opt,name=playbook_url_template,json=playbookUrlTemplate,proto3" json:"playbook_url_template,omitempty"`    // Default: ""
	// Default: Cloudprober alert "@alert@" for "@target@"
	SummaryTemplate string `protobuf:"bytes,6,opt,name=summary_template,json=summaryTemplate,proto3" json:"summary_template,omitempty"`
	// Default:
	// Cloudprober alert "@alert@" for "@target@":
	// Failures: @failures@ out of @total@ probes
	// Failing since: @since@
	// Probe: @probe@
	// Dashboard: @dashboard_url@
	// Playbook: @playbook_url@
	DetailsTemplate string `protobuf:"bytes,7,opt,name=details_template,json=detailsTemplate,proto3" json:"details_template,omitempty"` // Default: ""
	// Key values to be included in the alert. These fields are expanded
	// using the same template expansion rules as summary_template and
	// details_template (see above).
	OtherInfo map[string]string  `protobuf:"bytes,9,rep,name=other_info,json=otherInfo,proto3" json:"other_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Severity  AlertConf_Severity `protobuf:"varint,10,opt,name=severity,proto3,enum=cloudprober.alerting.AlertConf_Severity" json:"severity,omitempty"`
	// How often to repeat notification for the same alert. Default is 1hr.
	// To disable any kind of notification throttling, set this to 0.
	RepeatIntervalSec *int32 `protobuf:"varint,8,opt,name=repeat_interval_sec,json=repeatIntervalSec,proto3,oneof" json:"repeat_interval_sec,omitempty"` // Default: 1hr
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlertConf) Reset() {
	*x = AlertConf{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertConf) ProtoMessage() {}

func (x *AlertConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertConf.ProtoReflect.Descriptor instead.
func (*AlertConf) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{6}
}

func (x *AlertConf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertConf) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *AlertConf) GetNotify() *NotifyConfig {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *AlertConf) GetDashboardUrlTemplate() string {
	if x != nil {
		return x.DashboardUrlTemplate
	}
	return ""
}

func (x *AlertConf) GetPlaybookUrlTemplate() string {
	if x != nil {
		return x.PlaybookUrlTemplate
	}
	return ""
}

func (x *AlertConf) GetSummaryTemplate() string {
	if x != nil {
		return x.SummaryTemplate
	}
	return ""
}

func (x *AlertConf) GetDetailsTemplate() string {
	if x != nil {
		return x.DetailsTemplate
	}
	return ""
}

func (x *AlertConf) GetOtherInfo() map[string]string {
	if x != nil {
		return x.OtherInfo
	}
	return nil
}

func (x *AlertConf) GetSeverity() AlertConf_Severity {
	if x != nil {
		return x.Severity
	}
	return AlertConf_UNKNOWN_SEVERITY
}

func (x *AlertConf) GetRepeatIntervalSec() int32 {
	if x != nil && x.RepeatIntervalSec != nil {
		return *x.RepeatIntervalSec
	}
	return 0
}

type Opsgenie_Responder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*Opsgenie_Responder_Id
	//	*Opsgenie_Responder_Name
	Ref           isOpsgenie_Responder_Ref `protobuf_oneof:"ref"`
	Type          Opsgenie_Responder_Type  `protobuf:"varint,3,opt,name=type,proto3,enum=cloudprober.alerting.Opsgenie_Responder_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opsgenie_Responder) Reset() {
	*x = Opsgenie_Responder{}
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opsgenie_Responder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opsgenie_Responder) ProtoMessage() {}

func (x *Opsgenie_Responder) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opsgenie_Responder.ProtoReflect.Descriptor instead.
func (*Opsgenie_Responder) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Opsgenie_Responder) GetRef() isOpsgenie_Responder_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Opsgenie_Responder) GetId() string {
	if x != nil {
		if x, ok := x.Ref.(*Opsgenie_Responder_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *Opsgenie_Responder) GetName() string {
	if x != nil {
		if x, ok := x.Ref.(*Opsgenie_Responder_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *Opsgenie_Responder) GetType() Opsgenie_Responder_Type {
	if x != nil {
		return x.Type
	}
	return Opsgenie_Responder_UNKNOWN_RESPONDER
}

type isOpsgenie_Responder_Ref interface {
	isOpsgenie_Responder_Ref()
}

type Opsgenie_Responder_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type Opsgenie_Responder_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*Opsgenie_Responder_Id) isOpsgenie_Responder_Ref() {}

func (*Opsgenie_Responder_Name) isOpsgenie_Responder_Ref() {}

var File_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto protoreflect.FileDescriptor

var file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDesc = string([]byte{
	0x0a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x1a,
	0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x68, 0x74, 0x74,
	0x70, 0x72, 0x65, 0x71, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6d, 0x74, 0x70, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6d, 0x74, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6d, 0x74, 0x70, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x6d, 0x74, 0x70, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x6d, 0x74, 0x70, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x6d, 0x74, 0x70, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0xb2, 0x03, 0x0a, 0x08, 0x4f, 0x70, 0x73, 0x67, 0x65, 0x6e, 0x69, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x12, 0x48, 0x0a,
	0x0a, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x73, 0x67, 0x65, 0x6e, 0x69,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x55, 0x72, 0x6c,
	0x12, 0x32, 0x0a, 0x15, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x1a, 0xce, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x4f, 0x70, 0x73, 0x67, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x41, 0x4d, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x53, 0x43, 0x41, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x45, 0x10, 0x04, 0x42, 0x05,
	0x0a, 0x03, 0x72, 0x65, 0x66, 0x22, 0xa8, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x67, 0x65, 0x72, 0x44,
	0x75, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x13, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x76,
	0x56, 0x61, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x55, 0x72, 0x6c, 0x12, 0x32, 0x0a, 0x15,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x22, 0x57, 0x0a, 0x05, 0x53, 0x6c, 0x61, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x13, 0x77, 0x65,
	0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x55, 0x72, 0x6c, 0x45, 0x6e, 0x76, 0x56, 0x61, 0x72, 0x22, 0xd3, 0x02, 0x0a, 0x0c, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65,
	0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x3e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x72,
	0x5f, 0x64, 0x75, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x44, 0x75, 0x74, 0x79, 0x52, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x72, 0x44, 0x75, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x6c, 0x61, 0x63, 0x6b,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x6c,
	0x61, 0x63, 0x6b, 0x52, 0x05, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x12, 0x3a, 0x0a, 0x08, 0x6f, 0x70,
	0x73, 0x67, 0x65, 0x6e, 0x69, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x73, 0x67, 0x65, 0x6e, 0x69, 0x65, 0x52, 0x08, 0x6f, 0x70,
	0x73, 0x67, 0x65, 0x6e, 0x69, 0x65, 0x12, 0x47, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x72, 0x65, 0x71, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22,
	0x3d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xdf,
	0x05, 0x0a, 0x09, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x42, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65,
	0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x34, 0x0a, 0x16, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x75, 0x72,
	0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x14, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x55, 0x72, 0x6c, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x6f,
	0x6f, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x6f, 0x6f, 0x6b, 0x55,
	0x72, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x4d, 0x0a, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x72, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x44, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x28, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76,
	0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x01, 0x52, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x88, 0x01, 0x01, 0x1a, 0x3c, 0x0a, 0x0e, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52,
	0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x04, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63,
	0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_goTypes = []any{
	(Opsgenie_Responder_Type)(0), // 0: cloudprober.alerting.Opsgenie.Responder.Type
	(AlertConf_Severity)(0),      // 1: cloudprober.alerting.AlertConf.Severity
	(*Email)(nil),                // 2: cloudprober.alerting.Email
	(*Opsgenie)(nil),             // 3: cloudprober.alerting.Opsgenie
	(*PagerDuty)(nil),            // 4: cloudprober.alerting.PagerDuty
	(*Slack)(nil),                // 5: cloudprober.alerting.Slack
	(*NotifyConfig)(nil),         // 6: cloudprober.alerting.NotifyConfig
	(*Condition)(nil),            // 7: cloudprober.alerting.Condition
	(*AlertConf)(nil),            // 8: cloudprober.alerting.AlertConf
	(*Opsgenie_Responder)(nil),   // 9: cloudprober.alerting.Opsgenie.Responder
	nil,                          // 10: cloudprober.alerting.AlertConf.OtherInfoEntry
	(*proto.HTTPRequest)(nil),    // 11: cloudprober.utils.httpreq.HTTPRequest
}
var file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_depIdxs = []int32{
	9,  // 0: cloudprober.alerting.Opsgenie.responders:type_name -> cloudprober.alerting.Opsgenie.Responder
	2,  // 1: cloudprober.alerting.NotifyConfig.email:type_name -> cloudprober.alerting.Email
	4,  // 2: cloudprober.alerting.NotifyConfig.pager_duty:type_name -> cloudprober.alerting.PagerDuty
	5,  // 3: cloudprober.alerting.NotifyConfig.slack:type_name -> cloudprober.alerting.Slack
	3,  // 4: cloudprober.alerting.NotifyConfig.opsgenie:type_name -> cloudprober.alerting.Opsgenie
	11, // 5: cloudprober.alerting.NotifyConfig.http_notify:type_name -> cloudprober.utils.httpreq.HTTPRequest
	7,  // 6: cloudprober.alerting.AlertConf.condition:type_name -> cloudprober.alerting.Condition
	6,  // 7: cloudprober.alerting.AlertConf.notify:type_name -> cloudprober.alerting.NotifyConfig
	10, // 8: cloudprober.alerting.AlertConf.other_info:type_name -> cloudprober.alerting.AlertConf.OtherInfoEntry
	1,  // 9: cloudprober.alerting.AlertConf.severity:type_name -> cloudprober.alerting.AlertConf.Severity
	0,  // 10: cloudprober.alerting.Opsgenie.Responder.type:type_name -> cloudprober.alerting.Opsgenie.Responder.Type
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto != nil {
		return
	}
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[6].OneofWrappers = []any{}
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes[7].OneofWrappers = []any{
		(*Opsgenie_Responder_Id)(nil),
		(*Opsgenie_Responder_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_depIdxs,
		EnumInfos:         file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_enumTypes,
		MessageInfos:      file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_internal_alerting_proto_config_proto_depIdxs = nil
}
