// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/internal/httpreq/proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTTP method
type HTTPRequest_Method int32

const (
	HTTPRequest_GET     HTTPRequest_Method = 0
	HTTPRequest_POST    HTTPRequest_Method = 1
	HTTPRequest_PUT     HTTPRequest_Method = 2
	HTTPRequest_DELETE  HTTPRequest_Method = 3
	HTTPRequest_HEAD    HTTPRequest_Method = 4
	HTTPRequest_OPTIONS HTTPRequest_Method = 5
	HTTPRequest_PATCH   HTTPRequest_Method = 6
)

// Enum value maps for HTTPRequest_Method.
var (
	HTTPRequest_Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
		4: "HEAD",
		5: "OPTIONS",
		6: "PATCH",
	}
	HTTPRequest_Method_value = map[string]int32{
		"GET":     0,
		"POST":    1,
		"PUT":     2,
		"DELETE":  3,
		"HEAD":    4,
		"OPTIONS": 5,
		"PATCH":   6,
	}
)

func (x HTTPRequest_Method) Enum() *HTTPRequest_Method {
	p := new(HTTPRequest_Method)
	*p = x
	return p
}

func (x HTTPRequest_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HTTPRequest_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_enumTypes[0].Descriptor()
}

func (HTTPRequest_Method) Type() protoreflect.EnumType {
	return &file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_enumTypes[0]
}

func (x HTTPRequest_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HTTPRequest_Method.Descriptor instead.
func (HTTPRequest_Method) EnumDescriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescGZIP(), []int{0, 0}
}

type HTTPRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Url    string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method HTTPRequest_Method     `protobuf:"varint,2,opt,name=method,proto3,enum=cloudprober.utils.httpreq.HTTPRequest_Method" json:"method,omitempty"`
	// Data to be sent as request body. If there are multiple "data" fields, we combine
	// their values with a '&' in between. Note: 1) If data appears to be a valid json,
	// we automatically set the content-type header to "application/json", 2) If data
	// appears to be a query string we set content-type to
	// "application/x-www-form-urlencoded". Content type header can still be overridden
	// using the header field below.
	Data []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	// HTTP request headers
	Header        map[string]string `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPRequest) GetMethod() HTTPRequest_Method {
	if x != nil {
		return x.Method
	}
	return HTTPRequest_GET
}

func (x *HTTPRequest) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HTTPRequest) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDesc = "" +
	"\n" +
	"Fgithub.com/cloudprober/cloudprober/internal/httpreq/proto/config.proto\x12\x19cloudprober.utils.httpreq\"\xd5\x02\n" +
	"\vHTTPRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12E\n" +
	"\x06method\x18\x02 \x01(\x0e2-.cloudprober.utils.httpreq.HTTPRequest.MethodR\x06method\x12\x12\n" +
	"\x04data\x18\x03 \x03(\tR\x04data\x12J\n" +
	"\x06header\x18\x04 \x03(\v22.cloudprober.utils.httpreq.HTTPRequest.HeaderEntryR\x06header\x1a9\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x06Method\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\b\n" +
	"\x04HEAD\x10\x04\x12\v\n" +
	"\aOPTIONS\x10\x05\x12\t\n" +
	"\x05PATCH\x10\x06B;Z9github.com/cloudprober/cloudprober/internal/httpreq/protob\x06proto3"

var (
	file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_goTypes = []any{
	(HTTPRequest_Method)(0), // 0: cloudprober.utils.httpreq.HTTPRequest.Method
	(*HTTPRequest)(nil),     // 1: cloudprober.utils.httpreq.HTTPRequest
	nil,                     // 2: cloudprober.utils.httpreq.HTTPRequest.HeaderEntry
}
var file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_depIdxs = []int32{
	0, // 0: cloudprober.utils.httpreq.HTTPRequest.method:type_name -> cloudprober.utils.httpreq.HTTPRequest.Method
	2, // 1: cloudprober.utils.httpreq.HTTPRequest.header:type_name -> cloudprober.utils.httpreq.HTTPRequest.HeaderEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_depIdxs,
		EnumInfos:         file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_enumTypes,
		MessageInfos:      file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_internal_httpreq_proto_config_proto_depIdxs = nil
}
