syntax = "proto2";

package cloudprober.servers.udp;

option go_package = "github.com/cloudprober/cloudprober/internal/servers/udp/proto";

message ServerConf {
  required int32 port = 1;

  enum Type {
    // Echos the incoming packet back.
    ECHO = 0;

    // Discard the incoming packet. Return nothing.
    DISCARD = 1;
  }
  required Type type = 2;

  // Maximum UDP payload size, in bytes, that can be received. Must be between 1 and 65535.
  optional int32 max_payload_size = 3 [default = 4098];
}
