// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.2
// source: github.com/cloudprober/cloudprober/internal/rds/consul/proto/global.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GlobalOptions configures Consul settings that can be shared across
// both targets and surfacers.
type GlobalOptions struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Address           *string                  `protobuf:"bytes,1,opt,name=address,def=localhost:8500" json:"address,omitempty"`
	Datacenter        *string                  `protobuf:"bytes,2,opt,name=datacenter" json:"datacenter,omitempty"`
	Token             *string                  `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	Tls               *TLSConfig               `protobuf:"bytes,4,opt,name=tls" json:"tls,omitempty"`
	KubernetesService *KubernetesServiceConfig `protobuf:"bytes,5,opt,name=kubernetes_service,json=kubernetesService" json:"kubernetes_service,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for GlobalOptions fields.
const (
	Default_GlobalOptions_Address = string("localhost:8500")
)

func (x *GlobalOptions) Reset() {
	*x = GlobalOptions{}
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalOptions) ProtoMessage() {}

func (x *GlobalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GlobalOptions) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return Default_GlobalOptions_Address
}

func (x *GlobalOptions) GetDatacenter() string {
	if x != nil && x.Datacenter != nil {
		return *x.Datacenter
	}
	return ""
}

func (x *GlobalOptions) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *GlobalOptions) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *GlobalOptions) GetKubernetesService() *KubernetesServiceConfig {
	if x != nil {
		return x.KubernetesService
	}
	return nil
}

type TLSConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CaFile             *string                `protobuf:"bytes,1,opt,name=ca_file,json=caFile" json:"ca_file,omitempty"`
	CertFile           *string                `protobuf:"bytes,2,opt,name=cert_file,json=certFile" json:"cert_file,omitempty"`
	KeyFile            *string                `protobuf:"bytes,3,opt,name=key_file,json=keyFile" json:"key_file,omitempty"`
	InsecureSkipVerify *bool                  `protobuf:"varint,4,opt,name=insecure_skip_verify,json=insecureSkipVerify,def=0" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

const (
	Default_TLSConfig_InsecureSkipVerify = bool(false)
)

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TLSConfig) GetCaFile() string {
	if x != nil && x.CaFile != nil {
		return *x.CaFile
	}
	return ""
}

func (x *TLSConfig) GetCertFile() string {
	if x != nil && x.CertFile != nil {
		return *x.CertFile
	}
	return ""
}

func (x *TLSConfig) GetKeyFile() string {
	if x != nil && x.KeyFile != nil {
		return *x.KeyFile
	}
	return ""
}

func (x *TLSConfig) GetInsecureSkipVerify() bool {
	if x != nil && x.InsecureSkipVerify != nil {
		return *x.InsecureSkipVerify
	}
	return Default_TLSConfig_InsecureSkipVerify
}

type KubernetesServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,def=default" json:"namespace,omitempty"`
	ServiceName   *string                `protobuf:"bytes,2,opt,name=service_name,json=serviceName,def=consul" json:"service_name,omitempty"`
	Port          *string                `protobuf:"bytes,3,opt,name=port,def=8500" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

const (
	Default_KubernetesServiceConfig_Namespace   = string("default")
	Default_KubernetesServiceConfig_ServiceName = string("consul")
	Default_KubernetesServiceConfig_Port        = string("8500")
)

func (x *KubernetesServiceConfig) Reset() {
	*x = KubernetesServiceConfig{}
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesServiceConfig) ProtoMessage() {}

func (x *KubernetesServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KubernetesServiceConfig) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return Default_KubernetesServiceConfig_Namespace
}

func (x *KubernetesServiceConfig) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return Default_KubernetesServiceConfig_ServiceName
}

func (x *KubernetesServiceConfig) GetPort() string {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return Default_KubernetesServiceConfig_Port
}

var File_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto protoreflect.FileDescriptor

var file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDesc = []byte{
	0x0a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x64,
	0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6c, 0x22, 0x97, 0x02, 0x0a, 0x0d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x68, 0x6f, 0x73,
	0x74, 0x3a, 0x38, 0x35, 0x30, 0x30, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x2e, 0x72, 0x64, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x2e, 0x54, 0x4c, 0x53, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x03, 0x74, 0x6c, 0x73, 0x12, 0x5c, 0x0a, 0x12, 0x6b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x2e,
	0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x11, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65,
	0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x09, 0x54,
	0x4c, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x14, 0x69, 0x6e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x52, 0x12,
	0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x53, 0x6b, 0x69, 0x70, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x3a, 0x02, 0x18, 0x01, 0x22, 0x8a, 0x01, 0x0a, 0x18, 0x4b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x21, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x3a,
	0x06, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x3a, 0x04, 0x38, 0x35, 0x30, 0x30, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x3a, 0x02,
	0x18, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x72, 0x64, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32,
}

var (
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescData = file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDesc
)

func file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescData)
	})
	return file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_goTypes = []any{
	(*GlobalOptions)(nil),           // 0: cloudprober.rds.consul.GlobalOptions
	(*TLSConfig)(nil),               // 1: cloudprober.rds.consul.TLSConfig
	(*KubernetesServiceConfig)(nil), // 2: cloudprober.rds.consul.KubernetesServiceConfig
}
var file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_depIdxs = []int32{
	1, // 0: cloudprober.rds.consul.GlobalOptions.tls:type_name -> cloudprober.rds.consul.TLSConfig
	2, // 1: cloudprober.rds.consul.GlobalOptions.kubernetes_service:type_name -> cloudprober.rds.consul.KubernetesServiceConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_init() }
func file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_init() {
	if File_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto = out.File
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_rawDesc = nil
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_internal_rds_consul_proto_global_proto_depIdxs = nil
}
