// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/probes/starlark/proto/config.proto

package proto

import (
	proto2 "github.com/cloudprober/cloudprober/common/oauth/proto"
	proto1 "github.com/cloudprober/cloudprober/common/tlsconfig/proto"
	proto "github.com/cloudprober/cloudprober/metrics/payload/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProbeConf configures a Starlark probe.
//
// The probe runs a user-supplied Starlark function once per resolved target
// each interval. Wall time of the call becomes the probe's latency. Clean
// return is success; any unhandled error (including assertion failures) is
// failure.
type ProbeConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source of the Starlark code. Exactly one of source or source_file must
	// be set.
	Source     *string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	SourceFile *string `protobuf:"bytes,2,opt,name=source_file,json=sourceFile" json:"source_file,omitempty"`
	// Name of the entry-point function. It must accept a single argument: the
	// target. The target is a struct-like value mirroring fields from
	// cloudprober's targets/endpoint.Endpoint:
	//   target.name    (string)        — Endpoint.Name (host or IP)
	//   target.port    (int)           — Endpoint.Port (0 if none)
	//   target.ip      (string)        — Endpoint.IP, stringified ("" if nil)
	//   target.labels  (dict[str,str]) — Endpoint.Labels, frozen
	// Example:
	//   def probe(target):
	//       url = "http://%s:%d/healthz" % (target.name, target.port)
	//       env = target.labels.get("env", "unknown")
	//       ...
	// Defaults to "probe".
	EntryPoint *string `protobuf:"bytes,3,opt,name=entry_point,json=entryPoint,def=probe" json:"entry_point,omitempty"`
	// Variables exposed to the script via vars.get(name, default=None).
	//
	// Deliberately not named env_var: external/browser probes use that name
	// for "passed to subprocess env"; there's no subprocess here. For host
	// environment values, bake them in via the config-load template layer
	// (e.g. {{ envVar "PASS" }}).
	Vars map[string]string `protobuf:"bytes,4,rep,name=vars" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Custom metric emission options, used by the print_metric() builtin. Same
	// shape external + http probes already use, so kind (CUMULATIVE / GAUGE),
	// distribution-bucket configuration, in-cloudprober aggregation, and
	// additional labels all carry over with no Starlark-specific surface.
	OutputMetricsOptions *proto.OutputMetricsOptions `protobuf:"bytes,5,opt,name=output_metrics_options,json=outputMetricsOptions" json:"output_metrics_options,omitempty"`
	// TLS configs, keyed by a name the script uses to select one via the tls
	// kwarg on http calls:
	//   http.get(url, tls="internal")
	//
	// TLS is deliberately per-call, with no probe-wide default: a script
	// routinely hits several hosts in one run, and TLS settings are per-host in
	// a way a single config can't capture — ca_cert_file *replaces* the system
	// CA pool (so an internal CA breaks any public host the same script
	// touches), server_name is an SNI override for one host by definition, and
	// disable_cert_validation is rarely meant for every host. Name each config
	// here and select it explicitly:
	//   tls_configs {
	//     key: "legacy"
	//     value { disable_cert_validation: true }
	//   }
	//   def probe(target):
	//       http.get("https://public/healthz")                  # system roots
	//       http.get("https://legacy/healthz", tls="legacy")    # named config
	//
	// Omitting the tls kwarg means Go's TLS defaults (system CA pool, normal
	// validation), never "the only entry here" — a single config must still be
	// asked for by name. Passing an empty tls is an error rather than the
	// default, so a computed selector fails loudly:
	//   http.get(url, tls=target.labels["tls_profile"])  # missing label: error
	TlsConfigs map[string]*proto1.TLSConfig `protobuf:"bytes,6,rep,name=tls_configs,json=tlsConfigs" json:"tls_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// OAuth token sources, keyed by a name the script uses to select one. Same
	// oauth.Config message the HTTP probe uses, so every source (file, command,
	// HTTP token endpoint, GCE metadata, k8s token file, Google credentials,
	// self-signed JWT), plus refresh/expiry handling, carries over.
	//
	// Unlike the HTTP probe, tokens are NOT auto-injected: a Starlark script
	// routinely hits several hosts in one run, so it must ask for the token
	// explicitly and decide where it goes, via the oauth builtin:
	//   oauth.token(name="")  -- raw access token ("eyJ...")
	//   oauth.header(name="") -- formatted Authorization value ("Bearer eyJ...")
	// name may be omitted when exactly one config is present. Example:
	//   oauth_configs {
	//     key: "api"
	//     value { http_request { token_url: "https://issuer/token" ... } }
	//   }
	//   def probe(target):
	//       r = http.get(url, headers={"Authorization": oauth.header("api")})
	OauthConfigs map[string]*proto2.Config `protobuf:"bytes,7,rep,name=oauth_configs,json=oauthConfigs" json:"oauth_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Named proxy configs, keyed by a name the script uses to select one via
	// the proxy kwarg on http calls:
	//   http.get(url, proxy="corp")
	//
	// A named map, not a single probe-wide proxy_url: unlike the HTTP probe
	// (always exactly one request per execution, so one proxy_url covers every
	// call), a single Starlark probe execution can issue calls to several
	// distinct hosts, some needing a proxy and some not, or needing different
	// proxies. Name each one and select it explicitly, the same pattern
	// tls_configs already uses:
	//   proxy_configs {
	//     key: "corp"
	//     value { proxy_url: "http://proxy.internal:3128" }
	//   }
	//   def probe(target):
	//       http.get("https://public/healthz")                # direct
	//       http.get("https://internal/healthz", proxy="corp") # via proxy
	//
	// Omitting the proxy kwarg means a direct connection, never "the only entry
	// here" — a single config must still be asked for by name. Passing an
	// empty proxy is an error rather than direct, so a computed selector fails
	// loudly:
	//   http.get(url, proxy=target.labels["proxy_profile"])  # missing label: error
	//
	// tls and proxy are mutually exclusive on a single call: each selects from
	// its own independently-built client set, and there is no single client
	// that combines a named TLS config with a named proxy config.
	ProxyConfigs  map[string]*ProxyConfig `protobuf:"bytes,8,rep,name=proxy_configs,json=proxyConfigs" json:"proxy_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ProbeConf fields.
const (
	Default_ProbeConf_EntryPoint = string("probe")
)

func (x *ProbeConf) Reset() {
	*x = ProbeConf{}
	mi := &file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConf) ProtoMessage() {}

func (x *ProbeConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConf.ProtoReflect.Descriptor instead.
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeConf) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ProbeConf) GetSourceFile() string {
	if x != nil && x.SourceFile != nil {
		return *x.SourceFile
	}
	return ""
}

func (x *ProbeConf) GetEntryPoint() string {
	if x != nil && x.EntryPoint != nil {
		return *x.EntryPoint
	}
	return Default_ProbeConf_EntryPoint
}

func (x *ProbeConf) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *ProbeConf) GetOutputMetricsOptions() *proto.OutputMetricsOptions {
	if x != nil {
		return x.OutputMetricsOptions
	}
	return nil
}

func (x *ProbeConf) GetTlsConfigs() map[string]*proto1.TLSConfig {
	if x != nil {
		return x.TlsConfigs
	}
	return nil
}

func (x *ProbeConf) GetOauthConfigs() map[string]*proto2.Config {
	if x != nil {
		return x.OauthConfigs
	}
	return nil
}

func (x *ProbeConf) GetProxyConfigs() map[string]*ProxyConfig {
	if x != nil {
		return x.ProxyConfigs
	}
	return nil
}

// ProxyConfig configures a single named HTTP proxy for the proxy kwarg on
// http calls. See ProbeConf.proxy_configs.
type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyUrl      *string                `protobuf:"bytes,1,opt,name=proxy_url,json=proxyUrl" json:"proxy_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyConfig) GetProxyUrl() string {
	if x != nil && x.ProxyUrl != nil {
		return *x.ProxyUrl
	}
	return ""
}

var File_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDesc = "" +
	"\n" +
	"Egithub.com/cloudprober/cloudprober/probes/starlark/proto/config.proto\x12\x1bcloudprober.probes.starlark\x1aBgithub.com/cloudprober/cloudprober/common/oauth/proto/config.proto\x1aFgithub.com/cloudprober/cloudprober/common/tlsconfig/proto/config.proto\x1aEgithub.com/cloudprober/cloudprober/metrics/payload/proto/config.proto\"\x93\a\n" +
	"\tProbeConf\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_file\x18\x02 \x01(\tR\n" +
	"sourceFile\x12&\n" +
	"\ventry_point\x18\x03 \x01(\t:\x05probeR\n" +
	"entryPoint\x12D\n" +
	"\x04vars\x18\x04 \x03(\v20.cloudprober.probes.starlark.ProbeConf.VarsEntryR\x04vars\x12g\n" +
	"\x16output_metrics_options\x18\x05 \x01(\v21.cloudprober.metrics.payload.OutputMetricsOptionsR\x14outputMetricsOptions\x12W\n" +
	"\vtls_configs\x18\x06 \x03(\v26.cloudprober.probes.starlark.ProbeConf.TlsConfigsEntryR\n" +
	"tlsConfigs\x12]\n" +
	"\roauth_configs\x18\a \x03(\v28.cloudprober.probes.starlark.ProbeConf.OauthConfigsEntryR\foauthConfigs\x12]\n" +
	"\rproxy_configs\x18\b \x03(\v28.cloudprober.probes.starlark.ProbeConf.ProxyConfigsEntryR\fproxyConfigs\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a_\n" +
	"\x0fTlsConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .cloudprober.tlsconfig.TLSConfigR\x05value:\x028\x01\x1aZ\n" +
	"\x11OauthConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.cloudprober.oauth.ConfigR\x05value:\x028\x01\x1ai\n" +
	"\x11ProxyConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.cloudprober.probes.starlark.ProxyConfigR\x05value:\x028\x01\"*\n" +
	"\vProxyConfig\x12\x1b\n" +
	"\tproxy_url\x18\x01 \x01(\tR\bproxyUrlB:Z8github.com/cloudprober/cloudprober/probes/starlark/proto"

var (
	file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_goTypes = []any{
	(*ProbeConf)(nil),                  // 0: cloudprober.probes.starlark.ProbeConf
	(*ProxyConfig)(nil),                // 1: cloudprober.probes.starlark.ProxyConfig
	nil,                                // 2: cloudprober.probes.starlark.ProbeConf.VarsEntry
	nil,                                // 3: cloudprober.probes.starlark.ProbeConf.TlsConfigsEntry
	nil,                                // 4: cloudprober.probes.starlark.ProbeConf.OauthConfigsEntry
	nil,                                // 5: cloudprober.probes.starlark.ProbeConf.ProxyConfigsEntry
	(*proto.OutputMetricsOptions)(nil), // 6: cloudprober.metrics.payload.OutputMetricsOptions
	(*proto1.TLSConfig)(nil),           // 7: cloudprober.tlsconfig.TLSConfig
	(*proto2.Config)(nil),              // 8: cloudprober.oauth.Config
}
var file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_depIdxs = []int32{
	2, // 0: cloudprober.probes.starlark.ProbeConf.vars:type_name -> cloudprober.probes.starlark.ProbeConf.VarsEntry
	6, // 1: cloudprober.probes.starlark.ProbeConf.output_metrics_options:type_name -> cloudprober.metrics.payload.OutputMetricsOptions
	3, // 2: cloudprober.probes.starlark.ProbeConf.tls_configs:type_name -> cloudprober.probes.starlark.ProbeConf.TlsConfigsEntry
	4, // 3: cloudprober.probes.starlark.ProbeConf.oauth_configs:type_name -> cloudprober.probes.starlark.ProbeConf.OauthConfigsEntry
	5, // 4: cloudprober.probes.starlark.ProbeConf.proxy_configs:type_name -> cloudprober.probes.starlark.ProbeConf.ProxyConfigsEntry
	7, // 5: cloudprober.probes.starlark.ProbeConf.TlsConfigsEntry.value:type_name -> cloudprober.tlsconfig.TLSConfig
	8, // 6: cloudprober.probes.starlark.ProbeConf.OauthConfigsEntry.value:type_name -> cloudprober.oauth.Config
	1, // 7: cloudprober.probes.starlark.ProbeConf.ProxyConfigsEntry.value:type_name -> cloudprober.probes.starlark.ProxyConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_probes_starlark_proto_config_proto_depIdxs = nil
}
