// Configuration proto for File targets.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/targets/file/proto/config.proto

package proto

import (
	proto1 "github.com/cloudprober/cloudprober/internal/rds/file/proto"
	proto "github.com/cloudprober/cloudprober/internal/rds/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetsConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File that contains resources in either textproto or json format.
	// Example in textproto format:
	//
	//	resource {
	//	  name: "switch-xx-01"
	//	  ip: "10.11.112.3"
	//	  port: 8080
	//	  labels {
	//	    key: "device_type"
	//	    value: "switch"
	//	  }
	//	}
	//
	//	resource {
	//	  name: "switch-yy-01"
	//	  ip: "10.16.110.12"
	//	  port: 8080
	//	}
	FilePath *string                       `protobuf:"bytes,1,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	Filter   []*proto.Filter               `protobuf:"bytes,2,rep,name=filter" json:"filter,omitempty"`
	Format   *proto1.ProviderConfig_Format `protobuf:"varint,3,opt,name=format,enum=cloudprober.rds.file.ProviderConfig_Format" json:"format,omitempty"`
	// If specified, file will be re-read at the given interval.
	ReEvalSec     *int32 `protobuf:"varint,4,opt,name=re_eval_sec,json=reEvalSec" json:"re_eval_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetsConf) Reset() {
	*x = TargetsConf{}
	mi := &file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetsConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetsConf) ProtoMessage() {}

func (x *TargetsConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetsConf.ProtoReflect.Descriptor instead.
func (*TargetsConf) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *TargetsConf) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *TargetsConf) GetFilter() []*proto.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *TargetsConf) GetFormat() proto1.ProviderConfig_Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return proto1.ProviderConfig_Format(0)
}

func (x *TargetsConf) GetReEvalSec() int32 {
	if x != nil && x.ReEvalSec != nil {
		return *x.ReEvalSec
	}
	return 0
}

var File_github_com_cloudprober_cloudprober_targets_file_proto_config_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDesc = "" +
	"\n" +
	"Bgithub.com/cloudprober/cloudprober/targets/file/proto/config.proto\x12\x18cloudprober.targets.file\x1aGgithub.com/cloudprober/cloudprober/internal/rds/file/proto/config.proto\x1a?github.com/cloudprober/cloudprober/internal/rds/proto/rds.proto\"\xc0\x01\n" +
	"\vTargetsConf\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12/\n" +
	"\x06filter\x18\x02 \x03(\v2\x17.cloudprober.rds.FilterR\x06filter\x12C\n" +
	"\x06format\x18\x03 \x01(\x0e2+.cloudprober.rds.file.ProviderConfig.FormatR\x06format\x12\x1e\n" +
	"\vre_eval_sec\x18\x04 \x01(\x05R\treEvalSecB7Z5github.com/cloudprober/cloudprober/targets/file/proto"

var (
	file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_goTypes = []any{
	(*TargetsConf)(nil),               // 0: cloudprober.targets.file.TargetsConf
	(*proto.Filter)(nil),              // 1: cloudprober.rds.Filter
	(proto1.ProviderConfig_Format)(0), // 2: cloudprober.rds.file.ProviderConfig.Format
}
var file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_depIdxs = []int32{
	1, // 0: cloudprober.targets.file.TargetsConf.filter:type_name -> cloudprober.rds.Filter
	2, // 1: cloudprober.targets.file.TargetsConf.format:type_name -> cloudprober.rds.file.ProviderConfig.Format
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_targets_file_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_targets_file_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_targets_file_proto_config_proto_depIdxs = nil
}
