// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/metrics/proto/dist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dist defines a Distribution data type.
type Dist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Buckets:
	//
	//	*Dist_ExplicitBuckets
	//	*Dist_ExponentialBuckets
	Buckets       isDist_Buckets `protobuf_oneof:"buckets"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dist) Reset() {
	*x = Dist{}
	mi := &file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dist) ProtoMessage() {}

func (x *Dist) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dist.ProtoReflect.Descriptor instead.
func (*Dist) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescGZIP(), []int{0}
}

func (x *Dist) GetBuckets() isDist_Buckets {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *Dist) GetExplicitBuckets() string {
	if x != nil {
		if x, ok := x.Buckets.(*Dist_ExplicitBuckets); ok {
			return x.ExplicitBuckets
		}
	}
	return ""
}

func (x *Dist) GetExponentialBuckets() *ExponentialBuckets {
	if x != nil {
		if x, ok := x.Buckets.(*Dist_ExponentialBuckets); ok {
			return x.ExponentialBuckets
		}
	}
	return nil
}

type isDist_Buckets interface {
	isDist_Buckets()
}

type Dist_ExplicitBuckets struct {
	// Comma-separated list of lower bounds, where each lower bound is a float
	// value. Example: 0.5,1,2,4,8.
	ExplicitBuckets string `protobuf:"bytes,1,opt,name=explicit_buckets,json=explicitBuckets,proto3,oneof"`
}

type Dist_ExponentialBuckets struct {
	// Exponentially growing buckets
	ExponentialBuckets *ExponentialBuckets `protobuf:"bytes,2,opt,name=exponential_buckets,json=exponentialBuckets,proto3,oneof"`
}

func (*Dist_ExplicitBuckets) isDist_Buckets() {}

func (*Dist_ExponentialBuckets) isDist_Buckets() {}

// ExponentialBucket defines a set of num_buckets+2 buckets:
//
//	bucket[0] covers (−Inf, 0)
//	bucket[1] covers [0, scale_factor)
//	bucket[2] covers [scale_factor, scale_factor*base)
//	...
//	bucket[i] covers [scale_factor*base^(i−2), scale_factor*base^(i−1))
//	...
//	bucket[num_buckets+1] covers [scale_factor*base^(num_buckets−1), +Inf)
//
// NB: Base must be at least 1.01.
type ExponentialBuckets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScaleFactor   float32                `protobuf:"fixed32,1,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"` // default = 1.0
	Base          float32                `protobuf:"fixed32,2,opt,name=base,proto3" json:"base,omitempty"`                                  // default = 2
	NumBuckets    uint32                 `protobuf:"varint,3,opt,name=num_buckets,json=numBuckets,proto3" json:"num_buckets,omitempty"`     //default = 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExponentialBuckets) Reset() {
	*x = ExponentialBuckets{}
	mi := &file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExponentialBuckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExponentialBuckets) ProtoMessage() {}

func (x *ExponentialBuckets) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExponentialBuckets.ProtoReflect.Descriptor instead.
func (*ExponentialBuckets) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescGZIP(), []int{1}
}

func (x *ExponentialBuckets) GetScaleFactor() float32 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *ExponentialBuckets) GetBase() float32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *ExponentialBuckets) GetNumBuckets() uint32 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

var File_github_com_cloudprober_cloudprober_metrics_proto_dist_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDesc = "" +
	"\n" +
	";github.com/cloudprober/cloudprober/metrics/proto/dist.proto\x12\x13cloudprober.metrics\"\x9a\x01\n" +
	"\x04Dist\x12+\n" +
	"\x10explicit_buckets\x18\x01 \x01(\tH\x00R\x0fexplicitBuckets\x12Z\n" +
	"\x13exponential_buckets\x18\x02 \x01(\v2'.cloudprober.metrics.ExponentialBucketsH\x00R\x12exponentialBucketsB\t\n" +
	"\abuckets\"l\n" +
	"\x12ExponentialBuckets\x12!\n" +
	"\fscale_factor\x18\x01 \x01(\x02R\vscaleFactor\x12\x12\n" +
	"\x04base\x18\x02 \x01(\x02R\x04base\x12\x1f\n" +
	"\vnum_buckets\x18\x03 \x01(\rR\n" +
	"numBucketsB2Z0github.com/cloudprober/cloudprober/metrics/protob\x06proto3"

var (
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_goTypes = []any{
	(*Dist)(nil),               // 0: cloudprober.metrics.Dist
	(*ExponentialBuckets)(nil), // 1: cloudprober.metrics.ExponentialBuckets
}
var file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_depIdxs = []int32{
	1, // 0: cloudprober.metrics.Dist.exponential_buckets:type_name -> cloudprober.metrics.ExponentialBuckets
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_init() }
func file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_init() {
	if File_github_com_cloudprober_cloudprober_metrics_proto_dist_proto != nil {
		return
	}
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes[0].OneofWrappers = []any{
		(*Dist_ExplicitBuckets)(nil),
		(*Dist_ExponentialBuckets)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_metrics_proto_dist_proto = out.File
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_metrics_proto_dist_proto_depIdxs = nil
}
