syntax = "proto2";

package cloudprober.surfacer.otel;

import "github.com/cloudprober/cloudprober/internal/otel/proto/exporter.proto";

option go_package = "github.com/cloudprober/cloudprober/internal/surfacers/otel/proto";

message SurfacerConf {
  oneof exporter {
    // OTLP HTTP exporter.
    cloudprober.otel.HTTPExporter otlp_http_exporter = 1;

    // OTLP gRPC exporter.
    cloudprober.otel.GRPCExporter otlp_grpc_exporter = 2;
  }

  // How often metrics will be exported. Note that metrics are accumulated
  // internally and exported at this interval. Increasing this value will
  // increase the memory usage.
  optional int32 export_interval_sec = 3 [default = 10];

  // Prefix to use for metrics. Defaults to "cloudprober_".
  optional string metrics_prefix = 4 [default = "cloudprober_"];

  // Additional attributes to be added to all the metrics.
  message Attribute {
    optional string key = 1;
    optional string value = 2;
  }
  repeated Attribute resource_attribute = 5;
}
