// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/surfacers/testdata/testdata.proto

package testdata

import (
	proto "github.com/cloudprober/cloudprober/internal/surfacers/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FancySurfacer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FancySurfacer) Reset() {
	*x = FancySurfacer{}
	mi := &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FancySurfacer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FancySurfacer) ProtoMessage() {}

func (x *FancySurfacer) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FancySurfacer.ProtoReflect.Descriptor instead.
func (*FancySurfacer) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescGZIP(), []int{0}
}

func (x *FancySurfacer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type AnotherFancySurfacer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnotherFancySurfacer) Reset() {
	*x = AnotherFancySurfacer{}
	mi := &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnotherFancySurfacer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnotherFancySurfacer) ProtoMessage() {}

func (x *AnotherFancySurfacer) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnotherFancySurfacer.ProtoReflect.Descriptor instead.
func (*AnotherFancySurfacer) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescGZIP(), []int{1}
}

func (x *AnotherFancySurfacer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*proto.SurfacerDef)(nil),
		ExtensionType: (*FancySurfacer)(nil),
		Field:         200,
		Name:          "cloudprober.surfacer.testdata.fancy_surfacer",
		Tag:           "bytes,200,opt,name=fancy_surfacer",
		Filename:      "github.com/cloudprober/cloudprober/surfacers/testdata/testdata.proto",
	},
	{
		ExtendedType:  (*proto.SurfacerDef)(nil),
		ExtensionType: (*AnotherFancySurfacer)(nil),
		Field:         201,
		Name:          "cloudprober.surfacer.testdata.another_fancy_surfacer",
		Tag:           "bytes,201,opt,name=another_fancy_surfacer",
		Filename:      "github.com/cloudprober/cloudprober/surfacers/testdata/testdata.proto",
	},
}

// Extension fields to proto.SurfacerDef.
var (
	// optional cloudprober.surfacer.testdata.FancySurfacer fancy_surfacer = 200;
	E_FancySurfacer = &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_extTypes[0]
	// optional cloudprober.surfacer.testdata.AnotherFancySurfacer another_fancy_surfacer = 201;
	E_AnotherFancySurfacer = &file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_extTypes[1]
)

var File_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDesc = "" +
	"\n" +
	"Dgithub.com/cloudprober/cloudprober/surfacers/testdata/testdata.proto\x12\x1dcloudprober.surfacer.testdata\x1aHgithub.com/cloudprober/cloudprober/internal/surfacers/proto/config.proto\"#\n" +
	"\rFancySurfacer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x14AnotherFancySurfacer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:w\n" +
	"\x0efancy_surfacer\x12!.cloudprober.surfacer.SurfacerDef\x18\xc8\x01 \x01(\v2,.cloudprober.surfacer.testdata.FancySurfacerR\rfancySurfacer:\x8d\x01\n" +
	"\x16another_fancy_surfacer\x12!.cloudprober.surfacer.SurfacerDef\x18\xc9\x01 \x01(\v23.cloudprober.surfacer.testdata.AnotherFancySurfacerR\x14anotherFancySurfacerB7Z5github.com/cloudprober/cloudprober/surfacers/testdata"

var (
	file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_goTypes = []any{
	(*FancySurfacer)(nil),        // 0: cloudprober.surfacer.testdata.FancySurfacer
	(*AnotherFancySurfacer)(nil), // 1: cloudprober.surfacer.testdata.AnotherFancySurfacer
	(*proto.SurfacerDef)(nil),    // 2: cloudprober.surfacer.SurfacerDef
}
var file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_depIdxs = []int32{
	2, // 0: cloudprober.surfacer.testdata.fancy_surfacer:extendee -> cloudprober.surfacer.SurfacerDef
	2, // 1: cloudprober.surfacer.testdata.another_fancy_surfacer:extendee -> cloudprober.surfacer.SurfacerDef
	0, // 2: cloudprober.surfacer.testdata.fancy_surfacer:type_name -> cloudprober.surfacer.testdata.FancySurfacer
	1, // 3: cloudprober.surfacer.testdata.another_fancy_surfacer:type_name -> cloudprober.surfacer.testdata.AnotherFancySurfacer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_init() }
func file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_init() {
	if File_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_msgTypes,
		ExtensionInfos:    file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_extTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto = out.File
	file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_surfacers_testdata_testdata_proto_depIdxs = nil
}
