// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.5
// source: github.com/cloudprober/cloudprober/surfacers/internal/datadog/proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Surfacer config for datadog surfacer.
type SurfacerConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix to add to all metrics.
	Prefix *string `protobuf:"bytes,1,opt,name=prefix,def=cloudprober" json:"prefix,omitempty"`
	// Datadog API key. If not set, DD_API_KEY env variable is used.
	ApiKey *string `protobuf:"bytes,2,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	// Datadog APP key. If not set, DD_APP_KEY env variable is used.
	AppKey *string `protobuf:"bytes,3,opt,name=app_key,json=appKey" json:"app_key,omitempty"`
	// Datadog server, default: "api.datadoghq.com"
	Server *string `protobuf:"bytes,4,opt,name=server" json:"server,omitempty"`
	// The maximum number of metrics that will be published at one
	// time. Metrics will be stored locally in a cache until this
	// limit is reached. Datadog's SubmitMetric API has a maximum payload
	// size of 500 kilobytes (512000 bytes). Compressed payloads must have a
	// decompressed size of less than 5 megabytes (5242880 bytes).
	// Metrics will be published when the timer expires, or the buffer is
	// full, whichever happens first.
	MetricsBatchSize *int32 `protobuf:"varint,5,opt,name=metrics_batch_size,json=metricsBatchSize,def=1000" json:"metrics_batch_size,omitempty"`
	// The maximum amount of time to hold metrics in the buffer (above).
	// Metrics will be published when the timer expires, or the buffer is
	// full, whichever happens first.
	BatchTimerSec *int32 `protobuf:"varint,6,opt,name=batch_timer_sec,json=batchTimerSec,def=30" json:"batch_timer_sec,omitempty"`
	// Disable gzip compression of metric payload, when sending metrics to Datadog.
	// Compression is enabled by default.
	DisableCompression *bool `protobuf:"varint,7,opt,name=disable_compression,json=disableCompression" json:"disable_compression,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for SurfacerConf fields.
const (
	Default_SurfacerConf_Prefix           = string("cloudprober")
	Default_SurfacerConf_MetricsBatchSize = int32(1000)
	Default_SurfacerConf_BatchTimerSec    = int32(30)
)

func (x *SurfacerConf) Reset() {
	*x = SurfacerConf{}
	mi := &file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurfacerConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurfacerConf) ProtoMessage() {}

func (x *SurfacerConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurfacerConf.ProtoReflect.Descriptor instead.
func (*SurfacerConf) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *SurfacerConf) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return Default_SurfacerConf_Prefix
}

func (x *SurfacerConf) GetApiKey() string {
	if x != nil && x.ApiKey != nil {
		return *x.ApiKey
	}
	return ""
}

func (x *SurfacerConf) GetAppKey() string {
	if x != nil && x.AppKey != nil {
		return *x.AppKey
	}
	return ""
}

func (x *SurfacerConf) GetServer() string {
	if x != nil && x.Server != nil {
		return *x.Server
	}
	return ""
}

func (x *SurfacerConf) GetMetricsBatchSize() int32 {
	if x != nil && x.MetricsBatchSize != nil {
		return *x.MetricsBatchSize
	}
	return Default_SurfacerConf_MetricsBatchSize
}

func (x *SurfacerConf) GetBatchTimerSec() int32 {
	if x != nil && x.BatchTimerSec != nil {
		return *x.BatchTimerSec
	}
	return Default_SurfacerConf_BatchTimerSec
}

func (x *SurfacerConf) GetDisableCompression() bool {
	if x != nil && x.DisableCompression != nil {
		return *x.DisableCompression
	}
	return false
}

var File_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/cloudprober/cloudprober/surfacers/internal/datadog/proto/config.proto\x12\x1ccloudprober.surfacer.datadog\"\x8e\x02\n" +
	"\fSurfacerConf\x12#\n" +
	"\x06prefix\x18\x01 \x01(\t:\vcloudproberR\x06prefix\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x17\n" +
	"\aapp_key\x18\x03 \x01(\tR\x06appKey\x12\x16\n" +
	"\x06server\x18\x04 \x01(\tR\x06server\x122\n" +
	"\x12metrics_batch_size\x18\x05 \x01(\x05:\x041000R\x10metricsBatchSize\x12*\n" +
	"\x0fbatch_timer_sec\x18\x06 \x01(\x05:\x0230R\rbatchTimerSec\x12/\n" +
	"\x13disable_compression\x18\a \x01(\bR\x12disableCompressionBEZCgithub.com/cloudprober/cloudprober/surfacers/internal/datadog/proto"

var (
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_goTypes = []any{
	(*SurfacerConf)(nil), // 0: cloudprober.surfacer.datadog.SurfacerConf
}
var file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_init()
}
func file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_surfacers_internal_datadog_proto_config_proto_depIdxs = nil
}
