// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/probes/grpcext/proto/config.proto

package proto

import (
	proto "github.com/cloudprober/cloudprober/metrics/payload/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProbeConf configures an EXTERNAL_GRPC probe.
//
// The probe delegates each per-target probe run to a sidecar gRPC service
// implementing the cloudprober.probes.grpcext.Prober service (see
// service.proto). Cloudprober keeps scheduling, targets, metrics, and
// surfacers; the sidecar just runs the probe for one target and returns the
// result.
type ProbeConf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sidecar server address. Typically a co-located unix domain socket, e.g.
	// "unix:/var/run/cloudprober/sidecar.sock" (single colon — this form works
	// for both POSIX and Windows paths; see sidecar.Listen), but any gRPC
	// target string works, e.g. "localhost:9314".
	Server *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	// Probe type registered on the sidecar, e.g. "snowsql". A single sidecar
	// process can serve multiple probe types.
	ProbeType *string `protobuf:"bytes,2,opt,name=probe_type,json=probeType" json:"probe_type,omitempty"`
	// Type-specific configuration, passed to the sidecar as-is. Opaque to
	// cloudprober — it's decoded and validated by the sidecar. Typically JSON:
	//
	//	config: '{ "warehouse": "WH1", "query": "SELECT 1" }'
	Config *string `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
	// Options for parsing metrics returned by the sidecar. Sidecar returns
	// additional metrics as payload-format lines ("name{labels} value"); these
	// options control how they're parsed (metrics kind, aggregation,
	// distributions, etc.). Same surface as external and http probes.
	OutputMetricsOptions *proto.OutputMetricsOptions `protobuf:"bytes,4,opt,name=output_metrics_options,json=outputMetricsOptions" json:"output_metrics_options,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProbeConf) Reset() {
	*x = ProbeConf{}
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConf) ProtoMessage() {}

func (x *ProbeConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConf.ProtoReflect.Descriptor instead.
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeConf) GetServer() string {
	if x != nil && x.Server != nil {
		return *x.Server
	}
	return ""
}

func (x *ProbeConf) GetProbeType() string {
	if x != nil && x.ProbeType != nil {
		return *x.ProbeType
	}
	return ""
}

func (x *ProbeConf) GetConfig() string {
	if x != nil && x.Config != nil {
		return *x.Config
	}
	return ""
}

func (x *ProbeConf) GetOutputMetricsOptions() *proto.OutputMetricsOptions {
	if x != nil {
		return x.OutputMetricsOptions
	}
	return nil
}

var File_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDesc = "" +
	"\n" +
	"Dgithub.com/cloudprober/cloudprober/probes/grpcext/proto/config.proto\x12\x1acloudprober.probes.grpcext\x1aEgithub.com/cloudprober/cloudprober/metrics/payload/proto/config.proto\"\xc3\x01\n" +
	"\tProbeConf\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1d\n" +
	"\n" +
	"probe_type\x18\x02 \x01(\tR\tprobeType\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12g\n" +
	"\x16output_metrics_options\x18\x04 \x01(\v21.cloudprober.metrics.payload.OutputMetricsOptionsR\x14outputMetricsOptionsB9Z7github.com/cloudprober/cloudprober/probes/grpcext/proto"

var (
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_goTypes = []any{
	(*ProbeConf)(nil),                  // 0: cloudprober.probes.grpcext.ProbeConf
	(*proto.OutputMetricsOptions)(nil), // 1: cloudprober.metrics.payload.OutputMetricsOptions
}
var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_depIdxs = []int32{
	1, // 0: cloudprober.probes.grpcext.ProbeConf.output_metrics_options:type_name -> cloudprober.metrics.payload.OutputMetricsOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_init() }
func file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_init() {
	if File_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto = out.File
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_config_proto_depIdxs = nil
}
