// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: github.com/cloudprober/cloudprober/probes/grpcext/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target mirrors cloudprober's targets/endpoint.Endpoint.
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"` // Resolved IP, if available. Stringified, "" if none.
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Target) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Target) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Target) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ProbeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Probe type registered on the sidecar, e.g. "snowsql".
	ProbeType string  `protobuf:"bytes,1,opt,name=probe_type,json=probeType,proto3" json:"probe_type,omitempty"`
	Target    *Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Type-specific config, opaque to cloudprober (typically JSON). Same bytes
	// as the "config" field in the probe's cloudprober config.
	Config []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// Probe timeout. The RPC context carries the same deadline; this field
	// makes it available to sidecars whose language/framework doesn't surface
	// gRPC deadlines conveniently.
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Opaque per-target session handle, echoed back from the last
	// ProbeResponse for this target. Empty on first contact or after
	// cloudprober restart. The handle is a hint: on unknown/stale handle
	// (e.g. sidecar restarted), the sidecar re-initializes per-target state
	// and mints a fresh one.
	StateHandle   []byte `protobuf:"bytes,5,opt,name=state_handle,json=stateHandle,proto3" json:"state_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeRequest) GetProbeType() string {
	if x != nil {
		return x.ProbeType
	}
	return ""
}

func (x *ProbeRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ProbeRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProbeRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ProbeRequest) GetStateHandle() []byte {
	if x != nil {
		return x.StateHandle
	}
	return nil
}

type ProbeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Did the probe succeed? This is about the target, not the sidecar; see
	// internal_error below.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Probe latency as measured by the sidecar. Excludes the
	// cloudprober<->sidecar hop.
	Latency *durationpb.Duration `protobuf:"bytes,2,opt,name=latency,proto3" json:"latency,omitempty"`
	// internal_error indicates a sidecar/infra failure, NOT "target down".
	// Cloudprober records it separately (internal_errors metric) instead of
	// counting the run as a probe failure, so a broken sidecar doesn't look
	// like a broken target.
	InternalError bool   `protobuf:"varint,3,opt,name=internal_error,json=internalError,proto3" json:"internal_error,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Additional metrics in cloudprober payload format, one metric per line:
	//
	//	"name value" or "name{key=val,key2=val2} value"
	//
	// Parsed by cloudprober with metrics/payload (same as external and http
	// probes' custom metrics).
	Payload []string `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty"`
	// Session handle to store for this target and echo in the next
	// ProbeRequest. Sidecars that don't need per-target sessions leave this
	// empty.
	StateHandle   []byte `protobuf:"bytes,6,opt,name=state_handle,json=stateHandle,proto3" json:"state_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeResponse) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *ProbeResponse) GetInternalError() bool {
	if x != nil {
		return x.InternalError
	}
	return false
}

func (x *ProbeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeResponse) GetPayload() []string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProbeResponse) GetStateHandle() []byte {
	if x != nil {
		return x.StateHandle
	}
	return nil
}

var File_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto protoreflect.FileDescriptor

const file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDesc = "" +
	"\n" +
	"Egithub.com/cloudprober/cloudprober/probes/grpcext/proto/service.proto\x12\x1acloudprober.probes.grpcext\x1a\x1egoogle/protobuf/duration.proto\"\xc3\x01\n" +
	"\x06Target\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\x06labels\x18\x02 \x03(\v2..cloudprober.probes.grpcext.Target.LabelsEntryR\x06labels\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\fProbeRequest\x12\x1d\n" +
	"\n" +
	"probe_type\x18\x01 \x01(\tR\tprobeType\x12:\n" +
	"\x06target\x18\x02 \x01(\v2\".cloudprober.probes.grpcext.TargetR\x06target\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12!\n" +
	"\fstate_handle\x18\x05 \x01(\fR\vstateHandle\"\xd8\x01\n" +
	"\rProbeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\alatency\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\alatency\x12%\n" +
	"\x0einternal_error\x18\x03 \x01(\bR\rinternalError\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\apayload\x18\x05 \x03(\tR\apayload\x12!\n" +
	"\fstate_handle\x18\x06 \x01(\fR\vstateHandle2f\n" +
	"\x06Prober\x12\\\n" +
	"\x05Probe\x12(.cloudprober.probes.grpcext.ProbeRequest\x1a).cloudprober.probes.grpcext.ProbeResponseB9Z7github.com/cloudprober/cloudprober/probes/grpcext/protob\x06proto3"

var (
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescOnce sync.Once
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescData []byte
)

func file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescGZIP() []byte {
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescOnce.Do(func() {
		file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDesc)))
	})
	return file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDescData
}

var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_goTypes = []any{
	(*Target)(nil),              // 0: cloudprober.probes.grpcext.Target
	(*ProbeRequest)(nil),        // 1: cloudprober.probes.grpcext.ProbeRequest
	(*ProbeResponse)(nil),       // 2: cloudprober.probes.grpcext.ProbeResponse
	nil,                         // 3: cloudprober.probes.grpcext.Target.LabelsEntry
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_depIdxs = []int32{
	3, // 0: cloudprober.probes.grpcext.Target.labels:type_name -> cloudprober.probes.grpcext.Target.LabelsEntry
	0, // 1: cloudprober.probes.grpcext.ProbeRequest.target:type_name -> cloudprober.probes.grpcext.Target
	4, // 2: cloudprober.probes.grpcext.ProbeRequest.timeout:type_name -> google.protobuf.Duration
	4, // 3: cloudprober.probes.grpcext.ProbeResponse.latency:type_name -> google.protobuf.Duration
	1, // 4: cloudprober.probes.grpcext.Prober.Probe:input_type -> cloudprober.probes.grpcext.ProbeRequest
	2, // 5: cloudprober.probes.grpcext.Prober.Probe:output_type -> cloudprober.probes.grpcext.ProbeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_init() }
func file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_init() {
	if File_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDesc), len(file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_goTypes,
		DependencyIndexes: file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_depIdxs,
		MessageInfos:      file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_msgTypes,
	}.Build()
	File_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto = out.File
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_goTypes = nil
	file_github_com_cloudprober_cloudprober_probes_grpcext_proto_service_proto_depIdxs = nil
}
